version: '3.8'

services:
  planka_updates_service:
    build:
      context: ./planka-service
    ports:
      - "8000:80"
    environment:
      - ENV=development
      - PLANKA_URL=${PLANKA_URL}
      - PLANKA_EMAIL=${PLANKA_EMAIL}
      - PLANKA_PASSWORD=${PLANKA_PASSWORD}
      - UPDATE_INTERVAL=${UPDATE_INTERVAL}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
